In [1]:
import numpy as np

EX1

In [2]:
arr = np.arange(0, 10, 1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

EX2

In [3]:
arr = np.ones((3, 3)) > 0
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
arr = np.ones((3, 3), dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
arr = np.full((3, 3), fill_value=True, dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

EX3

In [6]:
arr = np.arange(0, 10)
print(arr[arr%2==1])

[1 3 5 7 9]


EX4

In [7]:
arr = np.arange(0, 10)
arr[arr%2==1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


EX5

In [8]:
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


EX6

In [9]:
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=0)
print('Result: \n', c)

Result: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


EX7

In [10]:
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=1)
print('C = ', c)

C =  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


EX8

In [11]:
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


EX9

In [12]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >=5)&(a<=10))
print ('result ', a[index])

result  [ 6  9 10]


EX10

In [13]:
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y
    
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


EX11

In [14]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print('Result: ', np.where(a<b, b, a))

Result:  [6 7 9 8 9 7 5]


EX12

In [15]:
import matplotlib.image as mpimg
img = mpimg.imread('dog.jpg')
gray_img_01 = (np.max(img[..., :3], axis=2) + np.min(img[..., :3], axis=2))/2
print(gray_img_01[0, 0])

102.5


EX13

In [16]:
img = mpimg.imread('dog.jpg')
gray_img_02 = np.mean(img[..., :3], axis=2)
print(gray_img_02[0, 0])

107.66666666666667


EX14

In [17]:
img = mpimg.imread('dog.jpg')
gray_img_03 = 0.21*img[..., 0] + 0.72*img[..., 1] + 0.07*img[..., 2]
print(gray_img_03[0, 0])

126.22999999999999


In [18]:
import pandas as pd
df = pd.read_csv('advertising.csv')
data = df.to_numpy()

EX15

In [19]:
sales_column = data[:, -1]
max_value = np.max(sales_column)
max_index = np.argmax(sales_column)
print(f'Max: {max_value} - Index: {max_index}')

Max: 27.0 - Index: 175


EX16

In [26]:
tv_column = data[:, 0]
mean_tv = np.mean(tv_column)
mean_tv

147.0425

EX17

In [21]:
num_records_sales_20 = np.sum(sales_column >= 20)
num_records_sales_20

40

EX18

In [22]:
radio_column = data[:, 1]
mean_radio_sales_15 = np.mean(radio_column[sales_column >= 15])
mean_radio_sales_15

26.22293577981651

EX19

In [23]:
newspaper_column = data[:, 2]
mean_newspaper = np.mean(newspaper_column)
sum_sales_newspaper_gt_mean = np.sum(sales_column[newspaper_column > mean_newspaper])
sum_sales_newspaper_gt_mean

1405.1

EX20

In [25]:
mean_sales = np.mean(sales_column)
scores = np.where(sales_column > mean_sales, 'Good', np.where(sales_column < mean_sales, 'Bad', 'Average'))
print(f'scores[7:10]: {scores[7:10]}')

scores[7:10]: ['Bad' 'Bad' 'Good']


EX21

In [27]:
closest_to_mean_sales = sales_column[np.abs(sales_column - mean_sales).argmin()]
scores_closest = np.where(sales_column > closest_to_mean_sales, 'Good', np.where(sales_column < closest_to_mean_sales, 'Bad', 'Average'))
print(f'scores_closest[7:10]: {scores_closest[7:10]}')

scores_closest[7:10]: ['Bad' 'Bad' 'Good']
