In [1]:
import numpy as np

In [2]:
# 1.1. Length of a vector
def compute_vector_length(vector):
    len_of_vector = np.linalg.norm(vector)
    return len_of_vector

# 1.2. Dot product
def compute_dot_product(vector1, vector2):
    result = np.dot(vector1, vector2)
    return result

# 1.3. Multiplying a vector by a matrix
def matrix_multi_vector(matrix, vector):
    result = np.dot(matrix, vector)
    return result

# 1.4. Multiplying a matrix by a matrix
def matrix_multi_matrix(matrix1, matrix2):
    result = np.dot(matrix1, matrix2)
    return result

# 1.5 Matrix inverse
def inverse_matrix(matrix):
    result = np.linalg.inv(matrix)
    return result

# 2.1 Eigenvector and eigenvalue
def compute_eigenvalues_eigenvectors(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors

# 3.1. Cosine Similarity
def compute_cosine(v1, v2):
    cos_sim = np.dot(v1, v2)/(np.linalg.norm(v1)*np.linalg.norm(v2))
    return cos_sim

In [7]:
import cv2

bg1_image = cv2.imread('GreenBackground.png', 1)
bg1_image = cv2.resize(bg1_image, (678, 381))

ob_image = cv2.imread('Object.png', 1)
ob_image = cv2.resize(ob_image, (678, 381))

bg2_image = cv2.imread('NewBackground.jpg', 1)
bg2_image = cv2.resize(bg2_image, (678, 381))

In [8]:
def compute_difference(bg_img, input_img):
    difference = cv2.absdiff(bg_img, input_img)
    difference_single_channel = cv2.cvtColor(difference, cv2.COLOR_BGR2GRAY)
    return difference_single_channel

# Display difference
difference_single_channel = compute_difference(bg1_image, ob_image)
difference_single_channel = compute_difference(bg1_image, ob_image)
cv2.imshow('Difference', difference_single_channel)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
def compute_binary_mask(difference_single_channel):
    _, difference_binary = cv2.threshold(difference_single_channel, 50, 255, cv2.THRESH_BINARY)
    return difference_binary

# Display binary mask
binary_mask = compute_binary_mask(difference_single_channel)
cv2.imshow('Binary Mask', binary_mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
def replace_background(bg1_image, bg2_image, ob_image):
    difference_single_channel = compute_difference(bg1_image, ob_image)
    binary_mask = compute_binary_mask(difference_single_channel)
    output = np.where(binary_mask[..., None] == 255, ob_image, bg2_image)
    return output

# Display final result
output_image = replace_background(bg1_image, bg2_image, ob_image)
cv2.imshow('Final Output', output_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

Multiple choice

Q1

In [11]:
vector = np.array([-2, 4, 9, 21])
result = compute_vector_length(vector)
print(round(result, 2))

23.28


Q2

In [12]:
v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1, 0])
result = compute_dot_product(v1, v2)
print(round(result, 2))

4


Q3

In [13]:
x = np.array([[1, 2], [3, 4]])
k = np.array([1, 2])
print('result\n', x.dot(k))

result
 [ 5 11]


Q4

In [14]:
x = np.array([[-1, 2], [3, -4]])
k = np.array([1, 2])
print('result\n', x @ k)

result
 [ 3 -5]


Q5

In [15]:
m = np.array([[-1, 1, 1], [0, -4, 9]])
v = np.array([0, 2, 1])
result = matrix_multi_vector(m, v)
print(result)

[3 1]


Q6

In [17]:
m1 = np.array([[0, 1, 2], [2, -3, 1]])
m2 = np.array([[1, -3], [6, 1], [0, -1]])
result = matrix_multi_matrix(m1, m2)
print(result)

[[  6  -1]
 [-16 -10]]


Q7

In [18]:
m1 = np.eye(3)
m2 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
result = m1 @ m2
print(result)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


Q8

In [19]:
m1 = np.eye(2)
m1 = np.reshape(m1, (-1, 4))[0]
m2 = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1 @ m2
print(result)

[5. 5. 5. 5.]


Q9

In [20]:
m1 = np.array([[1, 2], [3, 4]])
m1 = np.reshape(m1, (-1, 4), "F")[0]
m2 = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1 @ m2
print(result)

[29 29 29 29]


Q10

In [21]:
m1 = np.array([[-2, 6], [8, -4]])
result = inverse_matrix(m1)
print(result)

[[0.1  0.15]
 [0.2  0.05]]


Q11

In [22]:
matrix = np.array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


Q12

In [23]:
x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
result = compute_cosine(x, y)
print(round(result, 3))

0.577
